Feature/anti spam
dothemath-se/dothemath-app-backend pull request #1
Opened 2020-05-14 14:01 UTC by jonsandg

2020-05-14 15:46 UTC, memark requested changes
Det ser bra ut, men snygga till git-historiken.

2020-05-14 16:00 UTC, memark commented
Nu har det kommit nya commits i _master_, så du får rebasa på senaste _master_ också.

2020-05-14 17:25 UTC, jonsandg commented
Okok, har inte möjlighet att göra det under resten av kvällen dock. Har du möjlighet att göra det? Om vi vill bli klara ikväll dvs, gör det imorgon annars

2020-05-15 10:12 UTC, memark commented
Jag fixar det och mergar nu.

2020-05-15 10:13 UTC, memark approved these changes

2020-05-15 10:13 UTC, merged